"use client"

import { useState, useEffect } from "react"
import { captureElement } from "@/lib/capture"
import { Download, FileText, FileDown, School } from "lucide-react"
import { jsPDF } from "jspdf"

interface Question {
  id: string
  type: string
  text: string
  options?: string[]
  correctAnswer?: string
  points: number
}

interface ExamDownloadProps {
  exam: { title: string; description?: string; duration?: number }
  questions: Question[]
}

interface SchoolData {
  name: string
  motto?: string
  address?: string
  phone?: string
  email?: string
  logo?: string | null
}

const questionTypeLabels: Record<string, string> = {
  mcq: "Multiple Choice",
  true_false: "True / False",
  theory: "Theory",
  coding: "Coding",
}

export function ExamDownload({ exam, questions }: ExamDownloadProps) {
  const [loading, setLoading] = useState<string | null>(null)
  const [school, setSchool] = useState<SchoolData | null>(null)

  useEffect(() => {
    fetch("/api/school")
      .then((r) => r.json())
      .then((data: SchoolData) => setSchool(data))
      .catch(() => {})
  }, [])

  const schoolHeaderHtml = () => {
    if (!school) return ""
    const parts: string[] = []
    if (school.logo) {
      parts.push(
        `<div style="display:flex;align-items:center;gap:15px;margin-bottom:15px;">`,
        `<img src="${school.logo}" alt="School Logo" style="height:60px;width:auto;object-fit:contain;" />`,
        `<div>`
      )
    } else {
      parts.push(`<div style="text-align:center;margin-bottom:15px;">`)
    }
    parts.push(`<h1 style="font-size:22px;font-weight:bold;margin:0;color:#1a1a2e;">${school.name}</h1>`)
    if (school.motto) {
      parts.push(`<p style="font-style:italic;margin:3px 0 0;color:#666;font-size:13px;">${school.motto}</p>`)
    }
    const contactLine = [school.address, school.phone, school.email].filter(Boolean).join(" &nbsp;|&nbsp; ")
    if (contactLine) {
      parts.push(`<p style="margin:4px 0 0;color:#888;font-size:11px;">${contactLine}</p>`)
    }
    parts.push(`</div>`)
    if (school.logo) parts.push(`</div>`)
    return parts.join("")
  }

  const downloadPDF = async () => {
    setLoading("pdf")
    const element = document.createElement("div")
    element.style.cssText = "padding:40px;font-family:Arial,sans-serif;max-width:800px;margin:0 auto;background:white;color:#111;"
    element.innerHTML = `
      ${schoolHeaderHtml()}
      <hr style="border:none;border-top:3px solid #6366f1;margin:0 0 20px;" />
      <div style="text-align:center;margin-bottom:20px;">
        <h1 style="font-size:24px;font-weight:bold;margin:0 0 5px;color:#1a1a2e;">${exam.title}</h1>
        ${exam.description ? `<p style="color:#666;margin:0 0 10px;font-size:14px;">${exam.description}</p>` : ""}
        <p style="color:#888;margin:0;font-size:12px;">Duration: ${exam.duration || 0} minutes &nbsp;|&nbsp; Total Questions: ${questions.length}</p>
      </div>
      <div style="margin-bottom:20px;text-align:right;">
        <span style="background:#6366f1;color:white;padding:4px 12px;border-radius:4px;font-size:11px;font-weight:bold;">MARKING GUIDE</span>
      </div>
      ${questions.map((q, i) => `
        <div style="margin-bottom:24px;padding:16px;background:#f8f9ff;border-radius:8px;border-left:4px solid #6366f1;">
          <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
            <span style="font-weight:bold;font-size:14px;color:#1a1a2e;">Question ${i + 1}</span>
            <span style="font-size:12px;color:#888;">[${q.points} pts] &mdash; ${questionTypeLabels[q.type] || q.type}</span>
          </div>
          <p style="margin:0 0 10px;font-size:14px;line-height:1.5;color:#333;">${q.text}</p>
          ${q.options ? `
            <div style="margin-bottom:10px;font-size:13px;color:#555;">
              ${q.options.map((o, oi) => `<span style="display:inline-block;margin-right:12px;margin-bottom:4px;">${String.fromCharCode(65 + oi)}. ${o}</span>`).join("")}
            </div>
          ` : ""}
          ${q.correctAnswer ? `
            <div style="padding:8px 12px;background:#e8f5e9;border-radius:6px;font-size:13px;color:#2e7d32;border:1px solid #c8e6c9;">
              <strong>Answer:</strong> ${q.correctAnswer} <span style="color:#888;">(+${q.points} pts)</span>
            </div>
          ` : q.type === "theory" || q.type === "coding" ? `
            <div style="padding:8px 12px;background:#fff8e1;border-radius:6px;font-size:13px;color:#f57f17;border:1px solid #ffecb3;">
              <strong>Rubric:</strong> Award marks for correct logic and reasoning (max ${q.points} pts)
            </div>
          ` : ""}
        </div>
      `).join("")}
      <div style="text-align:center;padding-top:20px;border-top:2px solid #e0e0e0;font-size:11px;color:#999;">
        Generated by Access School Management Platform &bull; ${new Date().toLocaleDateString()}
      </div>
    `
    document.body.appendChild(element)
    try {
      const canvas = await captureElement(element, { scale: 2, backgroundColor: "#ffffff" })
      const imgData = canvas.toDataURL("image/png")
      const pdf = new jsPDF({ orientation: "portrait", unit: "px", format: [canvas.width, canvas.height] })
      pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height)
      pdf.save(`${exam.title.replace(/\s+/g, "_")}_Marking_Guide.pdf`)
    } finally {
      document.body.removeChild(element)
    }
    setLoading(null)
  }

  const downloadDOCX = () => {
    setLoading("docx")
    const schoolHeaderDocx = () => {
      if (!school) return ""
      let html = ""
      if (school.logo) {
        html += `<div style="display:flex;align-items:center;gap:15px;margin-bottom:15px;">`
        html += `<img src="${school.logo}" alt="School Logo" style="height:60px;width:auto;" />`
        html += `<div style="flex:1;">`
      }
      html += `<h1 style="font-size:22pt;font-weight:bold;margin:0;color:#1a1a2e;text-align:${school.logo ? 'left' : 'center'};">${school.name}</h1>`
      if (school.motto) {
        html += `<p style="font-style:italic;margin:3px 0 0;color:#666;font-size:12pt;text-align:${school.logo ? 'left' : 'center'};">${school.motto}</p>`
      }
      const contactLine = [school.address, school.phone, school.email].filter(Boolean).join("  |  ")
      if (contactLine) {
        html += `<p style="margin:4px 0 0;color:#888;font-size:10pt;text-align:${school.logo ? 'left' : 'center'};">${contactLine}</p>`
      }
      if (school.logo) {
        html += `</div></div>`
      }
      return html
    }
    const optionsHtml = (options?: string[]) => {
      if (!options || options.length === 0) return ""
      return options.map((o, i) => `<span style="display:inline-block;margin-right:20px;margin-bottom:4px;font-size:12pt;">${String.fromCharCode(65 + i)}. ${o}</span>`).join("")
    }
    const html = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <meta charset="UTF-8">
        <title>${exam.title}</title>
        <!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml><![endif]-->
        <style>
          body { font-family: 'Calibri', 'Arial', sans-serif; padding: 30px; color: #1a1a2e; }
          .header { text-align: center; padding-bottom: 15px; margin-bottom: 10px; }
          .header h1 { font-size: 22pt; margin: 0 0 5px; }
          .header .motto { font-style: italic; color: #666; font-size: 12pt; margin: 3px 0 0; }
          .header .contact { color: #888; font-size: 10pt; margin: 4px 0 0; }
          .exam-header { text-align: center; margin-bottom: 25px; }
          .exam-header h2 { font-size: 18pt; margin: 0 0 5px; }
          .exam-header p { color: #666; font-size: 11pt; margin: 0; }
          hr.divider { border: none; border-top: 3px solid #6366f1; margin: 0 0 15px; }
          .question { margin-bottom: 20px; padding: 10px 0; }
          .q-title { font-weight: bold; font-size: 12pt; margin-bottom: 6px; }
          .q-text { font-size: 12pt; margin-bottom: 8px; line-height: 1.5; }
          .options { font-size: 12pt; }
          .footer { text-align: center; border-top: 2px solid #e0e0e0; padding-top: 15px; font-size: 9pt; color: #999; margin-top: 30px; }
          .page-break { page-break-after: always; }
    </style>
  </head>
  <body>
    <div class="header">
      ${schoolHeaderDocx()}
    </div>
    <hr class="divider" />
    <div class="exam-header">
      <h2>${exam.title}</h2>
      ${exam.description ? `<p>${exam.description}</p>` : ""}
      <p>Duration: ${exam.duration || 0} minutes &nbsp;|&nbsp; Total Questions: ${questions.length}</p>
    </div>
    ${questions.map((q, i) => `
      <div class="question${(i + 1) % 5 === 0 ? ' page-break' : ''}">
        <div class="q-title">Question ${i + 1} <span style="font-weight:normal;color:#888;font-size:10pt;">[${q.points} pts]</span></div>
        <div class="q-text">${q.text}</div>
        ${q.options ? `<div class="options">${optionsHtml(q.options)}</div>` : q.type === "theory" || q.type === "coding" ? `<div style="min-height:60px;border-bottom:1px dashed #ccc;margin-top:10px;"></div>` : ""}
      </div>
    `).join("")}
    <div class="footer">Generated by Access School Management Platform &bull; ${new Date().toLocaleDateString()}</div>
  </body>
  </html>`

    const blob = new Blob([html], { type: "application/msword" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${exam.title.replace(/\s+/g, "_")}_Questions.docx`
    a.click()
    URL.revokeObjectURL(url)
    setLoading(null)
  }

  return (
    <div className="flex items-center gap-2">
      <button onClick={downloadPDF} disabled={loading !== null} className="flex items-center gap-2 rounded-lg border border-border bg-background px-4 py-2 text-sm font-medium transition-all hover:bg-muted disabled:opacity-50">
        <FileText className="h-4 w-4 text-red-500" />
        {loading === "pdf" ? "Generating..." : "PDF (Marking Guide)"}
      </button>
      <button onClick={downloadDOCX} disabled={loading !== null} className="flex items-center gap-2 rounded-lg border border-border bg-background px-4 py-2 text-sm font-medium transition-all hover:bg-muted disabled:opacity-50">
        <FileDown className="h-4 w-4 text-blue-500" />
        {loading === "docx" ? "Generating..." : "DOCX (Questions Only)"}
      </button>
    </div>
  )
}
