"use client"

import { useState, useEffect, useMemo } from "react"
import { motion } from "framer-motion"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Printer } from "lucide-react"
import { FileText, Download } from "lucide-react"
import { EmptyState } from "@/components/admin/EmptyState"
import { useParentChildren } from "@/hooks/useParentChildren"

export default function ParentDocumentsPage() {
  const { children, loading: childrenLoading } = useParentChildren()
  const [documents, setDocuments] = useState<any[]>([])
  const [students, setStudents] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  const linkedStudentIds = useMemo(() => children.map((c) => c.id), [children])

  useEffect(() => {
    if (childrenLoading || linkedStudentIds.length === 0) return
    setLoading(true)
    const childIds = linkedStudentIds.join(",")
    const classIds = [...new Set(children.map((c) => c.classId).filter(Boolean))].join(",")
    Promise.all([
      fetch(`/api/documents?studentIds=${childIds}`).then((r) => r.json()),
      fetch(`/api/students?classIds=${classIds}`).then((r) => r.json()),
    ]).then(([d, s]) => { setDocuments(Array.isArray(d) ? d : []); setStudents(Array.isArray(s) ? s : []); setLoading(false) })
      .catch(() => setLoading(false))
  }, [linkedStudentIds, childrenLoading])

  const getStudentName = (id: string) => { const s = students.find((s) => s.id === id); return s ? `${s.firstName} ${s.lastName}` : id }

  if (loading || childrenLoading) return <div className="p-4 md:p-6 space-y-4">{[1, 2, 3].map((i) => <div key={i} className="h-24 rounded-xl bg-muted animate-pulse" />)}</div>

  return (
    <div className="p-4 md:p-6 space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h2 className="text-2xl font-bold">Documents</h2>
        <p className="text-sm text-muted-foreground">Fee receipts, acceptance letters, and official documents</p>
      </motion.div>

      {documents.length === 0 ? (
        <EmptyState title="No documents" description="Documents will appear here when generated by the school" />
      ) : (
        <div className="space-y-3">
          {documents.slice().reverse().map((doc) => (
            <Card key={doc.id} className="border-0 glass-card">
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex h-9 w-9 md:h-10 md:w-10 items-center justify-center rounded-xl bg-primary/10">
                      <FileText className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <p className="font-medium">{doc.title}</p>
                      <p className="text-xs text-muted-foreground">{doc.reference} &bull; {getStudentName(doc.studentId)} &bull; {new Date(doc.generatedAt).toLocaleDateString()}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className="bg-green-500/15 text-green-600">{doc.status}</Badge>
                    <Button variant="ghost" size="icon" onClick={() => { const w = window.open("", "_blank"); if (w) { w.document.write(`<html><head><title>${doc.title}</title></head><body>Print preview</body></html>`); w.document.close(); w.print() } }}>
                      <Printer className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
